# Use root/example as user/password credentials
version: '3.1'

services:

  mongodb:
    image: mongo:5.0.17
    container_name: mongodb
    volumes:
      - ./:/app
    restart: always
    ports:
      - "27017:27017"

  redis:
    image: redis:7.0.8-alpine
    container_name: redis
    volumes:
      - ./:/app
    restart: always
    ports:
      - "6379:6379"