version: '3.9'
services:
#  backend:
#    build:
#        context: .
#        dockerfile: Dockerfile
#    volumes:
#      - .:/app
#    ports:
#      - '3000:3000'
#    tty: true
#    stdin_open: true
#    environment:
#      - HOST=${HOST}
##      - PORT=${PORT}
#      - MONGO_HOST=${MONGO_HOST}
#      - MONGO_PORT=${MONGO_PORT}
#      - MONGO_DATABASE=${MONGO_DATABASE}
#      - REDIS_HOST=${REDIS_HOST}
#      - REDIS_PORT=${REDIS_PORT}
#    depends_on:
#      - mongo
#      - redis
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis
    ports:
      - '6379:6379'

volumes:
  mongo_data: